python3 train-fan.py --dataset_path dataset/train\
    --padding SAME \
    --input_height 512 \
    --input_width 512 \
    --log_every_n_steps 250 \
    --save_summary_folder summaries/fan-model \
    --save_checkpoint_folder checkpoints/fan-model \
    --number_of_epochs 50 \
    --learning_rate 0.01 \
    --brightness_max_delta 0.15 \
    --saturation_lower 0.85 \
    --saturation_upper 1.15 \
    --hue_max_delta 0.12 \
    --contrast_lower 0.85 \
    --contrast_upper 1.15 \
    --batch_size 16
